### ISSUE TITLE
运行时发生了一些错误

### ISSUE THREAD

**Issue by lsj1111** [Persiefxy/Projector-correction#1]
当我执行检测Aruco码的函数时：函数如下
def Aruco_detect(gray):
    aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
    myByteList = []
    for idx, code in enumerate(aruco_dict.bytesList):
        code = code[np.newaxis, :, :]
        bits = cv2.aruco.Dictionary_getBitsFromByteList(code, 4)
        bits = cv2.flip(bits, 1)
        code = cv2.aruco.Dictionary_getByteListFromBits(bits)
        myByteList.append(code[0])
    myByteList = np.stack(myByteList, axis=0)
    dict1 = cv2.aruco.Dictionary(myByteList, 4)
    parameters =  cv2.aruco.DetectorParameters()
    result = {}
    cv2.imshow('image', gray)
    cv2.waitKey(0)
    corners, ids, _ = cv2.aruco.detectMarkers(gray, dict1, parameters=parameters)
    #assert (len(corners)!=0), print("Please retest")
    if len(corners) == 0:
        print("Please retest")
        raise AssertionError

    if ids is not None:
        corners_1 = np.array(corners).reshape(-1, 4, 2)
        center_points = np.mean(corners_1, 1)
    for i, idx in enumerate(ids):
        idx = int(idx)
        result[idx] = center_points[i]
    return result

报错提示：Traceback (most recent call last):
  File "test.py", line 96, in <module>
    martrix = matching_test(args.gray_folder, args.ph_coordinate, parameters, pro_size, cam_size)
  File "test.py", line 54, in matching_test
    anchors = Aruco_detect(images_list[45])
  File "test.py", line 29, in Aruco_detect
    raise AssertionError
AssertionError
Please retest

据我现在对代码的理解，似乎并没有创建Aruco码

**Comment by Persiefxy** [comment]
这只是一个检测已有Aruco码的代码，其中确实不包含生成Aruco码的方法
若要生成Aruco码，可参考以下方式：
import cv2
import numpy as np
import os
 
markersX =10           #X轴上标记的数量
markersY =10            #EY轴上标记的数量   本例生成1x1的棋盘
markerLength =100#标记的长度，单位是像素
markerSeparation =20#每个标记之间的间隔，单位像素
margins = markerSeparation #标记与边界之间的间隔
borderBits =10#标记的边界所占的bit位数
showImage =True
 
 
width = markersX *(markerLength + markerSeparation)- markerSeparation +2* margins
height =markersY *(markerLength + markerSeparation)- markerSeparation +2* margins
 
 
dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_1000)
# for idx, code in enumerate(dictionary.bytesList):
#     dict1 = cv2.aruco.Dictionary(code,4)
#     board = cv2.aruco.GridBoard((1,1), 0.015, 0.011, dict1)
#     img = cv2.aruco.Board.generateImage( board,(width,height), 0, 1)
#     print(img.shape)
#生成CharucoBoard
#board = cv2.aruco.CharucoBoard((3, 3), 0.015, 0.011, dictionary)
#生成aruco的格子，或者生成1个aruco,(1, 1)表示生成了1行1列
# dictionary = cv2.aruco.Dictionary_get(cv2.aruco.DICT_4X4_1000)
 
markerImage = np.zeros((800,800),dtype=np.uint8)
os.makedirs(f'./Aruco/',exist_ok=True)
for i inrange(1000):
    markerImage = cv2.aruco.drawMarker(dictionary, i,200, markerImage,1)
    firename=f'./Aruco/{i:04d}.png'
    cv2.imwrite(firename, markerImage)













在 2024-02-28 21:02:20，"lsj1111" ***@***.***> 写道：

当我执行检测Aruco码的函数时：函数如下
def Aruco_detect(gray):
aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
myByteList = []
for idx, code in enumerate(aruco_dict.bytesList):
code = code[np.newaxis, :, :]
bits = cv2.aruco.Dictionary_getBitsFromByteList(code, 4)
bits = cv2.flip(bits, 1)
code = cv2.aruco.Dictionary_getByteListFromBits(bits)
myByteList.append(code[0])
myByteList = np.stack(myByteList, axis=0)
dict1 = cv2.aruco.Dictionary(myByteList, 4)
parameters = cv2.aruco.DetectorParameters()
result = {}
cv2.imshow('image', gray)
cv2.waitKey(0)
corners, ids, _ = cv2.aruco.detectMarkers(gray, dict1, parameters=parameters)
#assert (len(corners)!=0), print("Please retest")
if len(corners) == 0:
print("Please retest")
raise AssertionError

if ids is not None:
    corners_1 = np.array(corners).reshape(-1, 4, 2)
    center_points = np.mean(corners_1, 1)
for i, idx in enumerate(ids):
    idx = int(idx)
    result[idx] = center_points[i]
return result


报错提示：Traceback (most recent call last):
File "test.py", line 96, in
martrix = matching_test(args.gray_folder, args.ph_coordinate, parameters, pro_size, cam_size)
File "test.py", line 54, in matching_test
anchors = Aruco_detect(images_list[45])
File "test.py", line 29, in Aruco_detect
raise AssertionError
AssertionError
Please retest

据我现在对代码的理解，似乎并没有创建Aruco码

**Comment by lsj1111** [comment]
好的，非常感谢你的解答，但是我对该方法还有一些困惑，您是否能给我一个联系方式让我请教一下。

**Comment by Persiefxy** [comment]
***@***.***，希望可以帮到您。
















在 2024-02-29 09:57:22，"lsj1111" ***@***.***> 写道：

好的，非常感谢你的解答，但是我对该方法还有一些困惑，您是否能给我一个联系方式让我请教一下。

**Comment by lsj1111** [comment]
> ***@***.***，希望可以帮到您。 在 2024-02-29 09:57:22，"lsj1111" ***@***.***> 写道： 好的，非常感谢你的解答，但是我对该方法还有一些困惑，您是否能给我一个联系方式让我请教一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

您是发了个邮箱地址吗，但它似乎被Github屏蔽了，
<img width="182" alt="Snipaste_2024-02-29_20-20-21" src="https://github.com/Persiefxy/Projector-correction/assets/86053092/c530063c-45e0-4f9a-b437-0828ae8e4834">

**Comment by lsj1111** [comment]
当我在运行代码时发现了一个未知的参数，parser.add_argument('--ph_coordinate', type=str, default = './ph_coordinate.txt',
 help='Projection image coordinates, eg: "./ph_coordinate.txt"')，似乎是投影仪的图像坐标，我没太理解这个投影仪图像坐标的意思，那么我该写什么内容到这个txt中呢。

**Comment by Persiefxy** [comment]
![image](https://github.com/Persiefxy/Projector-correction/assets/89825730/0902bbb8-f175-40b0-97f4-7d8df491ffa1)
ph_coordinate.txt的内容可以是以下形式
0.000000000000000000e+00 0.000000000000000000e+00 6.000000000000000000e+02
5.000000000000000000e+00 3.000000000000000000e+02 6.000000000000000000e+02
9.000000000000000000e+00 6.000000000000000000e+02 6.000000000000000000e+02
3.200000000000000000e+01 9.000000000000000000e+02 6.000000000000000000e+02
2.400000000000000000e+01 1.200000000000000000e+03 6.000000000000000000e+02
3.000000000000000000e+00 0.000000000000000000e+00 3.000000000000000000e+02
7.000000000000000000e+00 3.000000000000000000e+02 3.000000000000000000e+02
2.100000000000000000e+01 6.000000000000000000e+02 3.000000000000000000e+02
4.600000000000000000e+01 9.000000000000000000e+02 3.000000000000000000e+02
3.100000000000000000e+01 1.200000000000000000e+03 3.000000000000000000e+02
4.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00
8.000000000000000000e+00 3.000000000000000000e+02 0.000000000000000000e+00
2.900000000000000000e+01 6.000000000000000000e+02 0.000000000000000000e+00
1.900000000000000000e+01 9.000000000000000000e+02 0.000000000000000000e+00
3.300000000000000000e+01 1.200000000000000000e+03 0.000000000000000000e+00
其中第一列表示人为贴在板子上的每一个Aruco码的编号（通过检测得到），第二第三列分别为其对应的纵横坐标，表示每一个Aruco码在物理空间中的位置（不需要测量，满足相对位置关系即可）

**Comment by lsj1111** [comment]
我好像看的不是很明白，我理解的是摄像头和投影仪的坐标匹配靠的不是Gray码吗，但是看了您的解答好像这是Aruco码的功能，所以想要再请教一下。

**Comment by 3BPM** [comment]
请问一下/method/match.py 中 pro_cam_match函数中
  grid_x = np.linspace(0, cam_size[0]-1, cam_size[0])  # x coordinate range
    grid_y = np.linspace(0, cam_size[1]-1, cam_size[1])  # y coordinate range
    grid_x, grid_y = np.meshgrid(grid_x, grid_y)
    points_to_remap = np.column_stack((grid_x.flatten(), grid_y.flatten()))
    cam_pro = griddata(cam_know, pro_know, points_to_remap, method='cubic')
这个griddata后全是nan可能是什么原因呢？ 能否给一个当时拍摄的数据呢？
然后，如果摄像图片大小和投影显示大小不同，例如摄像头1920 1080 投影机1280 720  可能在哪些地方还要修改呢？

**Comment by Persiefxy** [comment]
我在test.py文件中分别定义了pro_size和cam_size您可以根据修改，pro_size表示投影图像的大小，cam_size表示相机分辨率。
pro_cam_match函数主要实现对 已经过gray码编解码后得到的部分相机和投影仪像素点之间的匹配关系，完成内插，得到相机内所有点在投影图像的对应坐标
![distribution](https://github.com/Persiefxy/Projector-correction/assets/89825730/da05b491-d4ea-42c9-a233-40c8bf6bbde2)

其中部分匹配关系的可视化如上，通过griddata可以完成整个cam_size内所有点的插值，并将横纵坐标分别记录在map_x和map_y中
















在 2024-03-27 22:56:19，"mingzr" ***@***.***> 写道：

请问一下/method/match.py 中 pro_cam_match函数中
grid_x = np.linspace(0, cam_size[0]-1, cam_size[0]) # x coordinate range
grid_y = np.linspace(0, cam_size[1]-1, cam_size[1]) # y coordinate range
grid_x, grid_y = np.meshgrid(grid_x, grid_y)
points_to_remap = np.column_stack((grid_x.flatten(), grid_y.flatten()))
cam_pro = griddata(cam_know, pro_know, points_to_remap, method='cubic')
这个griddata全是nan可能是什么原因呢？ 能否说明一下cam_pro的意义是什么？
如果摄像图片大小和投影显示大小不同，例如摄像头1920 1080 投影机1280 720 可能在哪些地方还要修改呢？

**Comment by 3BPM** [comment]
对不起 您的图片不知为何被吞掉了看不到，能否再发一份，本人邮箱是robertcjy@qq.com ![Screenshot_2024-03-27-23-55-33-805_com.android.chrome.jpg](https://github.com/Persiefxy/Projector-correction/assets/30543687/a0336ea2-0874-4952-8fe4-1549a46593aa)

**Comment by lsj1111** [comment]
如果我的投影仪是1280 720的，摄像头是1920 1080，那么假设我得到了1280 720个对应关系，但是在下面的代码中：
grid_x = np.linspace(0, cam_size[0]-1, cam_size[0]) # x coordinate range
grid_y = np.linspace(0, cam_size[1]-1, cam_size[1]) # y coordinate range
grid_x, grid_y = np.meshgrid(grid_x, grid_y)
points_to_remap = np.column_stack((grid_x.flatten(), grid_y.flatten()))
cam_pro = griddata(cam_know, pro_know, points_to_remap, method='cubic')
但是按照这里的代码，他会利用这1280 720个已知对应关系去计算剩下的未知值，但是1280*720总共就只有92万个像素坐标，但是摄像头是1920*1080（共有2000万个像素值），很明显是无法通过插值计算出来的，所以我对此处有疑问，还请解答

**Comment by Persiefxy** [comment]
在predict_unknow函数中，我们使用了cv2.finHomography和cv2.perspectiveTransform来对未匹配的点进行补齐
















在 2024-03-28 00:01:32，"lsj1111" ***@***.***> 写道：

如果我的投影仪是1280 720的，摄像头是1920 1080，那么假设我得到了1280 720个对应关系，但是在下面的代码中：
grid_x = np.linspace(0, cam_size[0]-1, cam_size[0]) # x coordinate range
grid_y = np.linspace(0, cam_size[1]-1, cam_size[1]) # y coordinate range
grid_x, grid_y = np.meshgrid(grid_x, grid_y)
points_to_remap = np.column_stack((grid_x.flatten(), grid_y.flatten()))
cam_pro = griddata(cam_know, pro_know, points_to_remap, method='cubic')
但是按照这里的代码，他会利用这1280 720个已知对应关系去计算剩下的未知值，但是1280720总共就只有92万个像素坐标，但是摄像头是19201080（共有2000万个像素值），很明显是无法通过插值计算出来的，所以我对此处有疑问，还请解答
